export const cores = {
    primary: '#0073e6',
    white: '#fff',
    orange: '#FFAC1C',
    whiteSmoke: '#f5f5f5',
	ghostWhite: '#f8f8ff',
    vermelho: '#EB0303',
    amarelo: '#FFF200',
    fundo: '#c1c1c1',
    menuItem: '#d1d1d1',
    laranja:'#FF6600',
    cinzaClaro: '#fafafa',
    branco: '#fff',
    dourado: '#FDCC0D',
 };